### ISSUE TITLE
Add updates

### ISSUE THREAD

**Issue by pkgprateek** [the-braveknight/Lenovo-G50-DSDT-Patch#2]
Please add updates for High Sierra 10.13.3 as rehabman has already included then 20 days back.
Its a request.

**Comment by the-braveknight** [comment]
Refer to my new guide at tonymacx86.com.
It supports both Z50 and G50 and is updated for 10.13.

Repo: https://github.com/the-braveknight/Lenovo-X50-macOS

**Comment by pkgprateek** [comment]
Can I use the same for 10.13.3 (latest update) and do i have to patch config.plist from Rehabman's repo like in the last work . or does it do it by the script itself??

Thanks for help

**Comment by the-braveknight** [comment]
See the guide here: https://www.tonymacx86.com/threads/guide-lenovo-z50-70-z40-70-g50-70-g40-70-using-clover-uefi.232823/

Most of the work is done automatically via the scripte.
